### PR TITLE
fix(hook): add missing encoding tag

### PR DESCRIPTION
**Pull request by msylgj**
This fixed commit f0d4a652b4096c644919d909c57927fb0d9e1e14

### CODE REVIEW

**Comment by 1715173329** [comment]
#834

**Comment by pan93412** [comment]
感覺是故意為之的，不然就是支援 gzip 的解壓縮？cc @cnbeining

**Comment by cnbeining** [comment]
I do not have specific preference on any proposed approach of fixing the encoding issue and would appreciate further explanations from the author, especially on:

- What is the behaviour of NM with the current HEAD during your development, and what are the changes with this commit applied?
- What's the added benefit - or mitigated issue - for explicitly accepting `gzip` as potential encoding, provided that the current HEAD of UNM does not have the logic to handle such encoding - and whether this assumption still holds between the 2 commits?

Looking forward to drill down this issue with the team.

Cheers,

**Comment by 1715173329** [comment]
As I mentioned in https://github.com/UnblockNeteaseMusic/server/pull/834#issuecomment-1229139956, and more broken functions were found by the committer, e.g. index banner, "心动模式", and "云村". Reverting #834 resolves the issue, but the other clients will be broken (based on original PR comments).
Maybe we need to handle gzipd response, or just some magic we ain't found.

**Comment by 1715173329** [comment]
Can confirm at least Android & iOS need this change, but it breaks the PC clients.

**Comment by 1715173329** [comment]
https://github.com/UnblockNeteaseMusic/server/blob/94bdf2488da9ff550cd336a745110209aa683657/src/request.js#L182-L185

We do handle gzipd response. I guess the latest PC clients use `sdch` for compression.

**Comment by 1715173329** [comment]
Tested on iOS 8.8.40, Windows 2.10.4, Android 6.0.0, all clients are happly.

**Comment by cnbeining** [comment]
In that case let’s do a permanent fix on decoding gzip.

**Pull request merged**
